### ISSUE TITLE
Grundfunktionen

### ISSUE THREAD

**Issue by nudl3r** [nudl3r/wannwas#2]
- Auswahl der Spiele per Twitch API

- Anmeldung per Steam/Twitch um doppeltes Abstimmen zu verhindern

- Täglich automatisch neues Voting mit Standard-Spielen wie z.B. R6

- Jeder kann abstimmen und eigene Vorschläge hinzufügen

Mit freundlichen Grüßen

**Comment by lellebebbl** [comment]
- Statistik über schon abgestimmte spiele

**Comment by nudl3r** [comment]
Besser für jede Funktion extra ein Issue öffnen :+1:
