### ISSUE TITLE
Datenbank? 

### ISSUE THREAD

**Issue by nudl3r** [nudl3r/wannwas#7]
MySQL? Oder wat

**Comment by lellebebbl** [comment]
sichi

**Comment by lellebebbl** [comment]
Sollen wir einen ORM benutzen? Doctrine?

**Comment by nudl3r** [comment]
Nie wirklich mit einem gearbeitet aber würde glaub schon Sinn machen

**Comment by lellebebbl** [comment]
Habs bis jetzt auch nur innerhalb eines framework genutzt, weiß nicht wie gut man das einbinden kann. aber ist schon unheimlich praktisch. Gerade da wir jea schon viel Datenbankenanfragen haben und ein mapping der entitäten gebrauchen könnten

**Comment by nudl3r** [comment]
Ich kenn halt Hibernate für Java ein bisschen, Doctrine sieht ähnlich aus.

Also ja, lass das benutzen :D

**Comment by lellebebbl** [comment]
Willst du das Übernehmen? Sollen wir uns auch noch eine Übersciht der Klassen machen die wir brauchen?

- Spiele
- User
- Umfrage

Edite den Post einfach für mehr

**Comment by nudl3r** [comment]
Ja kann ich machen.

Brauchen wir Spiele überhaupt? Eigentlich ja nur wenn sich jeder eine seine eigene Liste machen kann. Aber die könnte man eigentlich auch automatisch aus vorherigen Abstimmungen generieren.

Muss ich nachher mal überlegen.

An sich bräuchten wir nur die Umfrage bzw. Votes speichern und können darüber alles andere über die APIs ziehen. Korrgiere mich bitte wenn ich falsch liege :X

**Comment by lellebebbl** [comment]
Achso jo das passt. jetzt weiß ich auch glaub wie das mit der Twitch API gemeint ist. Find ich gut. User bräuchten wir dann trotzdem. Allein schon wegen der identifikation

**Comment by nudl3r** [comment]
Bei Twitch kann man ja z.B. auch wenn man streamt angeben welches Spiel man streamt, mit Auto-Korrektur. Also gibst z.B. Rainbow ein und bekommst Rainbow Six vorgeschlagen. So hätte ich mir das vorgestellt wenn man ein Spiel zur Umfrage hinzufügen will.

Was muss man vom User sonst in der Datenbank alles speichern? Authentifizierung läuft ja dann über die Steam-API und bei den Votes könnte man die Steam-ID dazu mitspeichern.

**Comment by lellebebbl** [comment]
ja das stimmt. dann machen wirs erstmal minimal und können es dann ja immernoch erweitern :+1: 

Ich hab übrigens gerade mal die Doctrine integration übernommen. Wollte gerade mal ein Projekt starten und dachte ich richte alle sgleich mal lauffähig ein

**Comment by lellebebbl** [comment]
So ist gemacht. Alle Konfigurationen in bootstrap.php anpassen, also die wegen der datenbank
